title: "Gwenaël PLEDEL"
url: "https://vzsca.github.io"
baseurl: "/Portfolio-Gwenael"
description: "Étudiant en BTS SIO, 1re année, intéressé par la cybersécurité et le pentest."
email: "gwenael.pledel@gmail.com"
linkedin: "https://www.linkedin.com/in/gwenael-pledel/"

lang: fr

collections:
  projets:
    output: true
    permalink: /projets/:name/

defaults:
  - scope:
      path: ""
      type: projets
    values:
      layout: projet

exclude:
  - README.md
  - LICENSE

future: true
